server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        host: ${HOST_NAME}
        __path__: /var/log/*log

  - job_name: containers
    static_configs:
    - targets:
      - localhost
      labels:
        job: containerlogs
        host: ${HOST_NAME}
        __path__: /var/lib/docker/containers/*/*log

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
        host: ${HOST_NAME}
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
